# Generated by Django 4.2.5 on 2023-09-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/no_image.png', upload_to='media/posts_images'),
        ),
    ]
